{{- $appProtocol := semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.serviceName . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations}}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  {{ if ne (.Values.service.type) ("NodePort") }}
  clusterIP: None
  {{ end }}
  {{- if .Values.topologyKeys }}
  topologyKeys:
    {{- toYaml .Values.topologyKeys | nindent 4 }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.websocket.enabled }}
  - name: websocket
    port: {{ .Values.websocket.port }}
    {{- if $appProtocol }}
    appProtocol: tcp
    {{- end }}
  {{- end }}
  - name: client
    port: 4222
    {{ if .Values.service.client.nodePort }}
    nodePort: {{ .Values.service.client.nodePort }}
    {{ end }}
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  - name: cluster
    port: 6222
    {{ if .Values.service.cluster.nodePort }}
    nodePort: {{ .Values.service.cluster.nodePort }}
    {{ end }}
    {{- if .Values.appProtocol.enabled }}
    appProtocol: tcp
    {{- end }}
  - name: monitor
    port: 8222
    {{ if .Values.service.monitoring.nodePort }}
    nodePort: {{ .Values.service.monitoring.nodePort }}
    {{ end }}
    {{- if .Values.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
  - name: {{ .Values.exporter.portName }}
    port: 7777
    {{- if $appProtocol }}
    appProtocol: http
    {{- end }}
  - name: leafnodes
    port: {{ .Values.leafnodes.port }}
    {{- if $appProtocol }}
    appProtocol: tcp
    {{- end }}
  - name: gateways
    port: {{ .Values.gateway.port }}
    {{- if $appProtocol }}
    appProtocol: tcp
    {{- end }}
  {{- if .Values.mqtt.enabled }}
  - name: mqtt
    port: 1883
    {{- if $appProtocol }}
    appProtocol: tcp
    {{- end }}
  {{- end }}
